<?php

namespace Metadata\Tests\Cache;

use Metadata\ClassMetadata;
use Metadata\Cache\FileCache;
use org\bovigo\vfs\vfsStream;
use org\bovigo\vfs\vfsStreamDirectory;

class FileCacheTest extends \PHPUnit_Framework_TestCase
{
    /** @var  vfsStreamDirectory */
    private $root;
    /** @var  FileCache */
    private $cache;

    public function setUp()
    {
        $this->root = vfsStream::setup('root', 0777);
        $this->cache = $cache = new FileCache(vfsStream::url('root'));

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testLoadEvictPutClassMetadataFromInCache()
    {
        $this->assertNull($this->cache->loadClassMetadataFromCache($refl = new \ReflectionClass('Metadata\Tests\Fixtures\TestObject')));
        $this->cache->putClassMetadataInCache($metadata = new ClassMetadata('Metadata\Tests\Fixtures\TestObject'));

        $this->assertEquals($metadata, $this->cache->loadClassMetadataFromCache($refl));

        $this->cache->evictClassMetadataFromCache($refl);
        $this->assertNull($this->cache->loadClassMetadataFromCache($refl));
    }

    /**
     * @expectedException \RuntimeException
     */
    public function testThrowExceptionIfNotWritable()
    {
        $this->root->chmod(0555);

        $this->cache->putClassMetadataInCache($metadata = new ClassMetadata('Metadata\Tests\Fixtures\TestObject'));
    }
}